# Generated by Django 5.2.4 on 2025-07-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resturanttenant',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resturanttenant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
