# Generated by Django 5.2.4 on 2026-02-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resturanttenant",
            name="on_trial",
            field=models.BooleanField(default=True),
        ),
    ]
