# Generated by Django 5.2.4 on 2026-03-29 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="inventory",
            old_name="descripton",
            new_name="description",
        ),
        migrations.RemoveField(
            model_name="inventory",
            name="items",
        ),
        migrations.RemoveField(
            model_name="inventorylog",
            name="quantity",
        ),
        migrations.AddField(
            model_name="inventorylog",
            name="action",
            field=models.CharField(
                choices=[("in", "IN"), ("adjust", "Adjust"), ("out", "OUT")],
                default=1,
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="inventorylog",
            name="new_quantity",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="inventorylog",
            name="previous_quantity",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="inventory",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="inventory.category"
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="units",
            field=models.CharField(
                choices=[
                    ("kg", "Kilogram"),
                    ("g", "Gram"),
                    ("ltr", "Liter"),
                    ("pcs", "Pieces"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="inventorylog",
            name="inventory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="inventory.inventory"
            ),
        ),
        migrations.AlterField(
            model_name="inventorylog",
            name="used_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
