# Generated by Django 5.2.4 on 2026-04-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("reserved", "Reserved"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("new", "New"),
                ],
                default="completed",
            ),
        ),
    ]
